# Generated by Django 5.0.1 on 2024-01-21 22:10

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название навыка')),
            ],
            options={
                'db_table': 'skill',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название вакансии')),
                ('salary', models.IntegerField(verbose_name='Зарплата')),
                ('area_name', models.TextField(verbose_name='Город')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата создания вакансии')),
            ],
            options={
                'db_table': 'vacancy',
            },
        ),
        migrations.CreateModel(
            name='VacancySkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Akaka.skill')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Akaka.vacancy')),
            ],
            options={
                'db_table': 'vacancy_skill',
                'unique_together': {('vacancy', 'skill')},
            },
        ),
    ]
